# Streamlit version: 1.10.0


[logger]

# String format for logging messages. If logger.datetimeFormat is set, logger messages will default to `%(asctime)s.%(msecs)03d %(message)s`. See [Python's documentation](https://docs.python.org/2.6/library/logging.html#formatter-objects) for available attributes.
# Default: "%(asctime)s %(message)s"
messageFormat = "%(asctime)s %(levelname)s %(module)s::%(funcName)s: %(message)s"


[runner]

# Allows you to type a variable or string by itself in a single line of Python code to write it to the app.
# Default: true
magicEnabled = false


[server]

# The port where the server will listen for browser connections.
# Default: 8501
port = 8501  # Needs to be defined, to be able to get the port for curl-testing the app


[theme]

# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
base = "dark"
