# Streamlit version: 1.10.0


[logger]

# Level of logging: 'error', 'warning', 'info', or 'debug'.
# Default: 'info'
level = "debug"

# String format for logging messages. If logger.datetimeFormat is set, logger messages will default to
#   `%(asctime)s.%(msecs)03d %(message)s
#`. See [Python's documentation](https://docs.python.org/2.6/library/logging.html#formatter-objects) for available
# attributes.
# Default: "%(asctime)s %(message)s"
messageFormat = "%(asctime)s %(levelname)s %(module)s::%(funcName)s: %(message)s"


[runner]

# Allows you to type a variable or string by itself in a single line of Python code to write it to the app.
# Default: true
magicEnabled = false

# Install a Python tracer to allow you to stop or pause your script at any point and introspect it. As a side-effect,
# this slows down your script's execution.
# Default: false
installTracer = false


[server]

# List of folders that should not be watched for changes. This impacts both "Run on Save" and @st.cache.
# Relative paths will be taken as relative to the current working directory.
# Example: ['/home/user1/env', 'relative/path/to/folder']
# Default: []
folderWatchBlacklist = []

# Automatically rerun script when the file is modified on disk.
# Default: false
runOnSave = false

# The address where the server will listen for client and browser connections. Use this if you want to bind the server
# to a specific address. If set, the server will only be accessible from this address, and not from any aliases
# (like localhost).
# Default: (unset)
# address =

# The port where the server will listen for browser connections.
# Default: 8501
port = 8501

# The base path for the URL where Streamlit should be served from.
# Default: ""
baseUrlPath = ""

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 5

# Max size, in megabytes, of messages that can be sent via the WebSocket connection.
# Default: 200
maxMessageSize = 5


[browser]

# Internet address where users should point their browsers in order to connect to the app. Can be IP address or DNS name
# and path.
# This is used to:
#   - Set the correct URL for CORS and XSRF protection purposes.
#   - Show the URL on the terminal
#   - Open the browser
# Default: 'localhost'
serverAddress = "localhost"

# Whether to send usage statistics to Streamlit.
# Default: true
gatherUsageStats = true

# Port where users should point their browsers in order to connect to the app.
# This is used to: - Set the correct URL for CORS and XSRF protection purposes. - Show the URL on the terminal - Open the browser
# Default: whatever value is set in server.port.
serverPort = 8501


[theme]

# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
base = "dark"

# Primary accent color for interactive elements.
# primaryColor =

# Background color for the main content area.
# backgroundColor =

# Background color used for the sidebar and most interactive widgets.
# secondaryBackgroundColor =

# Color used for almost all text.
# textColor =

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# font =
